# Generated by Django 2.1.7 on 2019-03-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sinceWhen', models.DateTimeField()),
                ('tillWhen', models.DateTimeField()),
            ],
            options={
                'ordering': ('id', 'created', 'sinceWhen', 'tillWhen'),
            },
        ),
    ]
